### ISSUE TITLE
License expired problem

### ISSUE THREAD

**Issue by ThomasKraaibeek** [dapor2000/docker-kerio-connect#2]
Hi!
I am using your docker image for testing purposes and i'm facing some issues.
Last week i had no problem logging in to the imap server via gnutls-cli. Now i'm trying to login and it fails with the message `* BYE Server license expired` after the handshake was completed. Is this image bound to a license, which actually expired? Can i get a new license somehow? A fresh install of the image didn't help.

Thanks for your help!

**Comment by dapor2000** [comment]
Hi,


as default the server start with a "trial-licence" from 30 days.
Kerio Connect  is a commercial product.


Regards 
Frank

__________________________________________________________________________________________

Facebook? --> https://pod.dapor.net

Whatsapp? --> https://riot.dapor.org 

 - nonprofit, privacy aware, user-owned, distributed social networks -



 Von:   Thomas Kraaibeek <notifications@github.com> 
 An:   dapor2000/docker-kerio-connect <docker-kerio-connect@noreply.github.com> 
 Kopie:   Subscribed <subscribed@noreply.github.com> 
 Gesendet:   10.11.2020 14:56 
 Betreff:   [dapor2000/docker-kerio-connect] License expired problem (#2) 


 
Hi!
 I am using your docker image for testing purposes and i'm facing some issues.
 Last week i had no problem logging in to the imap server via gnutls-cli. Now i'm trying to login and it fails with the message * BYE Server license expired after the handshake was completed. Is this image bound to a license, which actually expired? Can i get a new license somehow? A fresh install of the image didn't help. 
Thanks for your help!

**Comment by ThomasKraaibeek** [comment]
Hi Frank, thanks for the quick reply.
I tried removing the container and removing the image and pulling it from the docker hub again, to start over with a fresh trial license. That doesn't seem to be working. Any ideas?

Thanks again,
Thomas

**Comment by dapor2000** [comment]
no sorry
Am 10. Nov. 2020, um 16:07, Thomas Kraaibeek <notifications@github.com> schrieb:

Hi Frank, thanks for the quick reply.
I tried removing the container and removing the image and pulling it from the docker hub again, to start over with a fresh trial license. That doesn't seem to be working. Any ideas?
Thanks again,
Thomas

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dapor2000/docker-kerio-connect/issues/2#issuecomment-724761837",
"url": "https://github.com/dapor2000/docker-kerio-connect/issues/2#issuecomment-724761837",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
